### PR TITLE
Set compiler for PHP 8.3

### PR DESCRIPTION
**Pull request by derickr**

### CODE REVIEW

**Comment by wo80** [comment]
@cmb69 FYI, version 8.3 <del>officially</del> released today.

**Comment by derickr** [comment]
PHP 8.3 hasn't been released until it's announced.

**Comment by cedricziel** [comment]
I think it's there - https://www.php.net/releases/8.3/en.php

**Comment by asgrim** [comment]
@derickr oops? :thinking:

**Comment by wo80** [comment]
@asgrim It seems the new place to go is https://github.com/php/setup-php-sdk

**Comment by asgrim** [comment]
@wo80 oh thank you! I hadn't spotted that one :ok_hand: I appreciate the heads up

**Pull request closed without merging**
